"""Add crawler models

Revision ID: 363380e26e50
Revises: 59aaaf5b7362
Create Date: 2026-07-04 07:43:54.039147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363380e26e50'
down_revision: Union[str, Sequence[str], None] = '59aaaf5b7362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('document_chunks_tsv_idx'), table_name='document_chunks', postgresql_using='gin')
    op.drop_index(op.f('idx_document_chunks_fts'), table_name='document_chunks', postgresql_using='gin')
    op.add_column('documents', sa.Column('source_url', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('content_hash', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_documents_source_url'), 'documents', ['source_url'], unique=True)
    op.drop_index(op.f('idx_faqs_embedding'), table_name='faqs', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_faqs_fts'), table_name='faqs', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_faqs_fts'), 'faqs', ['fts_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_faqs_embedding'), 'faqs', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_documents_source_url'), table_name='documents')
    op.drop_column('documents', 'last_crawled_at')
    op.drop_column('documents', 'content_hash')
    op.drop_column('documents', 'source_url')
    op.create_index(op.f('idx_document_chunks_fts'), 'document_chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('document_chunks_tsv_idx'), 'document_chunks', ['tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
