"""Add crawler queue models

Revision ID: 600_add_crawler_queue
Revises: 363380e26e50
Create Date: 2026-07-05 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '600_add_crawler_queue'
down_revision: Union[str, Sequence[str], None] = '363380e26e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Use raw SQL with IF NOT EXISTS so this is idempotent when
    # init_db() / Base.metadata.create_all() already created the tables.
    conn = op.get_bind()
    conn.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS crawler_jobs (
            job_type TEXT NOT NULL,
            status   TEXT NOT NULL DEFAULT 'idle',
            crawled_count INTEGER DEFAULT 0,
            max_pages     INTEGER DEFAULT 0,
            current_url   TEXT,
            last_run      TIMESTAMP WITH TIME ZONE,
            PRIMARY KEY (job_type)
        )
    """))
    conn.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS crawler_queue (
            id       SERIAL PRIMARY KEY,
            job_type TEXT NOT NULL REFERENCES crawler_jobs(job_type) ON DELETE CASCADE,
            url      TEXT NOT NULL,
            status   TEXT NOT NULL DEFAULT 'pending',
            CONSTRAINT uq_crawler_queue_job_url UNIQUE (job_type, url)
        )
    """))
    conn.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS ix_crawler_queue_id       ON crawler_queue (id)"
    ))
    conn.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS ix_crawler_queue_job_type ON crawler_queue (job_type)"
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crawler_queue_job_type'), table_name='crawler_queue')
    op.drop_index(op.f('ix_crawler_queue_id'), table_name='crawler_queue')
    op.drop_table('crawler_queue')
    op.drop_table('crawler_jobs')
    # ### end Alembic commands ###
