"""Add crawler queue models

Revision ID: 600_add_crawler_queue
Revises: 363380e26e50
Create Date: 2026-07-05 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '600_add_crawler_queue'
down_revision: Union[str, Sequence[str], None] = '363380e26e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawler_jobs',
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False, server_default='idle'),
    sa.Column('crawled_count', sa.Integer(), nullable=True, server_default='0'),
    sa.Column('max_pages', sa.Integer(), nullable=True, server_default='0'),
    sa.Column('current_url', sa.Text(), nullable=True),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('job_type')
    )
    op.create_table('crawler_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False, server_default='pending'),
    sa.ForeignKeyConstraint(['job_type'], ['crawler_jobs.job_type'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_type', 'url', name='uq_crawler_queue_job_url')
    )
    op.create_index(op.f('ix_crawler_queue_id'), 'crawler_queue', ['id'], unique=False)
    op.create_index(op.f('ix_crawler_queue_job_type'), 'crawler_queue', ['job_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crawler_queue_job_type'), table_name='crawler_queue')
    op.drop_index(op.f('ix_crawler_queue_id'), table_name='crawler_queue')
    op.drop_table('crawler_queue')
    op.drop_table('crawler_jobs')
    # ### end Alembic commands ###
